apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
spec:
  generators:
    - git:
        repoURL: https://github.com/lostinopensrc/homelab-argocd-applicationset.git
        revision: main
        files:
          - path: "tenants-discovery/**/config.json"
  template:
    metadata:
      name: '{{tenant.id}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/lostinopensrc/homelab-argocd-applicationset.git
        targetRevision: main
        path: 'tenants/{{tenant.id}}'
        helm:
          valueFiles:
            - {{tenant.id}}.yaml
      destination:
        server: '{{k8s_cluster.address}}'
        namespace: '{{k8s_cluster.namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true